services:
  - type: web
    name: adhd-progressive-api
    env: python
    rootDir: .          # o 'backend' si tu main.py está dentro de esa carpeta
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MODEL_PATH
        value: ./artifacts/rf_snap_sim.joblib
