services:
  - type: web
    name: adhd-progressive-api
    env: python
    rootDir: .    # cámbialo si tu main.py está en subcarpeta
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
